networks:
  homeserver:
    driver: bridge

services:
  immich-server:
    image: ghcr.io/immich-app/immich-server:release
    container_name: immich_server
    command: ["start.sh", "immich"]
    env_file:
      - secrets.env
    environment:
      DB_USERNAME: ${IMMICH_DB_USERNAME}
      DB_PASSWORD: ${IMMICH_DB_PASSWORD}
      DB_DATABASE_NAME: ${IMMICH_DB_NAME}
      DB_HOSTNAME: database
    volumes:
      - ${DATA_ROOT}/immich/library:/usr/src/app/upload
    ports:
      - "2283:3001"
    depends_on:
      - redis
      - database
    networks:
      - homeserver
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1g

  immich-microservices:
    image: ghcr.io/immich-app/immich-server:release
    container_name: immich_microservices
    command: ["start.sh", "microservices"]
    env_file:
      - secrets.env
    environment:
      DB_USERNAME: ${IMMICH_DB_USERNAME}
      DB_PASSWORD: ${IMMICH_DB_PASSWORD}
      DB_DATABASE_NAME: ${IMMICH_DB_NAME}
      DB_HOSTNAME: database
    volumes:
      - ${DATA_ROOT}/immich/library:/usr/src/app/upload
    depends_on:
      - redis
      - database
    networks:
      - homeserver
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1g

  redis:
    image: redis:7
    container_name: immich_redis
    networks:
      - homeserver
    restart: unless-stopped

  database:
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:bcf63357191b76a916ae5eb93464d65c07511da41e3bf7a8416db519b40b1c23
    container_name: immich_postgres
    env_file:
      - secrets.env
    environment:
      POSTGRES_USER: ${IMMICH_DB_USERNAME}
      POSTGRES_PASSWORD: ${IMMICH_DB_PASSWORD}
      POSTGRES_DB: ${IMMICH_DB_NAME}
    volumes:
      - ${DATA_ROOT}/immich/postgres:/var/lib/postgresql/data
    networks:
      - homeserver
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512m

  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    environment:
      TZ: ${TZ}
    volumes:
      - ${DATA_ROOT}/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8123:8123"
    networks:
      - homeserver
    restart: unless-stopped
